# SPDX-License-Identifier: GPL-3.0
#
# Regenerated on every build (see the meshtastic_build_id_gen target in
# ../CMakeLists.txt): capture a short, developer-facing build identity into a
# header. Invoked as:
#   cmake -DSRC_DIR=<src> -DOUT=<hdr> -P gen_build_id.cmake
#
# MESHTASTIC_BUILD_ID   = `git describe --always --dirty` (short SHA, "-dirty"
#                         when the tree has uncommitted changes) — tells you the
#                         commit AND whether it is a dirty dev build.
# MESHTASTIC_BUILD_TIME = UTC "MMDD-HHMM" — tells rebuilds of the same tree apart.
#
# The header is only rewritten when its contents change, so a no-op rebuild does
# not needlessly recompile.

find_package(Git QUIET)

set(MT_ID "nogit")
if(GIT_FOUND)
  execute_process(
    COMMAND ${GIT_EXECUTABLE} -C "${SRC_DIR}" describe --always --dirty --abbrev=8
    OUTPUT_VARIABLE MT_ID
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(NOT _rc EQUAL 0 OR MT_ID STREQUAL "")
    set(MT_ID "nogit")
  endif()
endif()

string(TIMESTAMP MT_TIME "%m%d-%H%M" UTC)

set(_content "/* generated by gen_build_id.cmake — do not edit */\n")
string(APPEND _content "#pragma once\n")
string(APPEND _content "#define MESHTASTIC_BUILD_ID \"${MT_ID}\"\n")
string(APPEND _content "#define MESHTASTIC_BUILD_TIME \"${MT_TIME}\"\n")

set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
  file(WRITE "${OUT}" "${_content}")
endif()
