CONFIG_MESHTASTIC_NODE_LONG_NAME="T-Watch S3"
CONFIG_MESHTASTIC_NODE_SHORT_NAME="TWS3"

CONFIG_I2C=y
CONFIG_REGULATOR=y
CONFIG_FUEL_GAUGE=y

CONFIG_MESHTASTIC_FUEL_GAUGE=y
CONFIG_MESHTASTIC_TX_POWER=4
