/* Known-answer vectors harvested from upstream Meshtastic firmware.
 *
 * GENERATED by tools/vectors/harvest.py -- DO NOT EDIT BY HAND.
 * Regenerate:  python3 tools/vectors/harvest.py --upstream <firmware-tree>
 *
 * Every value below was produced by COMPILING AND RUNNING upstream's own
 * code, or by mechanically parsing an upstream table -- never by
 * reimplementing an algorithm. That is what makes these vectors able to
 * catch a symmetric error that the self-loopback tests cannot.
 *
 * Upstream: firmware @ ff951059c
 * Verbatim regions (sha256 of extracted text):
 *   xor_hash                 src/mesh/Channels.cpp:27  77646cb87b60e197
 *   djb2_hash                src/mesh/RadioInterface.cpp:908  a40dc5227198efd3
 *   modem_preset_to_params   src/mesh/MeshRadio.h:203  ae57bdd95cbc01a9
 *   init_nonce               src/mesh/CryptoEngine.cpp:428  80e7d0462008af80
 *   preset_display_name      src/DisplayFormatters.cpp:4  745b97c5d1836239
 */

#ifndef MESHTASTIC_VECTORS_H_
#define MESHTASTIC_VECTORS_H_

#include <stdint.h>

/* --- Channel-name xor hash (parity: crypto #1) ------------------------
 * Channel hash = xorHash(name) ^ xorHash(psk). The port currently
 * hardcodes the name "LongFast", so every non-default channel hashes
 * wrong and stock nodes silently ignore the traffic.
 */
struct mt_vec_name_hash { const char *name; uint8_t hash; };
static const struct mt_vec_name_hash mt_vec_name_hashes[] = {
	{ "", 0 },
	{ "LongFast", 10 },
	{ "LongSlow", 13 },
	{ "MediumFast", 29 },
	{ "MediumSlow", 26 },
	{ "ShortFast", 114 },
	{ "ShortSlow", 117 },
	{ "LongMod", 108 },
	{ "ShortTurbo", 12 },
	{ "admin", 111 },
	{ "gpio", 17 },
	{ "mqtt", 28 },
	{ "serial", 0 },
	{ "Test Channel", 85 },
	{ "channel-with-dash", 127 },
	{ "UPPER", 66 },
	{ "lower", 99 },
	{ "MiXeD123", 109 },
	{ "\u00fcn\u00efc\u00f8d\u00e9", 107 },
	{ "0123456789AB", 2 },
};

/* --- PSK xor hash (second half of the channel hash) ------------------ */
struct mt_vec_psk_hash { const char *label; uint8_t hash; };
static const struct mt_vec_psk_hash mt_vec_psk_hashes[] = {
	{ "empty", 0 },
	{ "default_index_1", 1 },
	{ "index_2", 2 },
	{ "aes128_zero", 0 },
	{ "aes128_ff", 0 },
	{ "aes128_counting", 0 },
	{ "aes256_counting", 0 },
};

/* --- djb2 hash, frequency-slot selection (parity: radio D3) ----------
 * NOTE: this is a DIFFERENT function from the channel xorHash above.
 * Conflating the two is silent and produces a node on the wrong
 * frequency that still believes it is configured correctly.
 */
struct mt_vec_djb2 { const char *name; uint32_t hash; };
static const struct mt_vec_djb2 mt_vec_djb2_hashes[] = {
	{ "", 5381u },
	{ "LongFast", 130429955u },
	{ "LongSlow", 130908986u },
	{ "MediumFast", 1461075348u },
	{ "MediumSlow", 1461554379u },
	{ "ShortFast", 603668899u },
	{ "ShortSlow", 604147930u },
	{ "LongMod", 3908476213u },
	{ "ShortTurbo", 2758524545u },
	{ "admin", 252902542u },
	{ "gpio", 2090300660u },
	{ "mqtt", 2090517739u },
	{ "serial", 461651653u },
	{ "Test Channel", 1184747838u },
	{ "channel-with-dash", 3536591540u },
	{ "UPPER", 237919953u },
	{ "lower", 266353742u },
	{ "MiXeD123", 4071817202u },
	{ "\u00fcn\u00efc\u00f8d\u00e9", 278246354u },
	{ "0123456789AB", 2063936373u },
};

/* --- Modem preset -> SF/BW/CR (parity: radio D2) ---------------------
 * The port is frozen at LongFast; these are the parameters stock
 * firmware uses for every preset, narrow and wide.
 */
struct mt_vec_preset {
	const char *name;
	int preset_enum;
	uint8_t wide;
	uint8_t sf;
	uint32_t bw_hz;
	uint8_t cr;
};
static const struct mt_vec_preset mt_vec_presets[] = {
	{ "LITE_FAST", 10, 0, 9, 125000u, 5 },
	{ "LITE_FAST", 10, 1, 9, 125000u, 5 },
	{ "LITE_SLOW", 11, 0, 10, 125000u, 5 },
	{ "LITE_SLOW", 11, 1, 10, 125000u, 5 },
	{ "LONG_FAST", 0, 0, 11, 250000u, 5 },
	{ "LONG_FAST", 0, 1, 11, 812500u, 5 },
	{ "LONG_MODERATE", 7, 0, 11, 125000u, 8 },
	{ "LONG_MODERATE", 7, 1, 11, 406250u, 8 },
	{ "LONG_SLOW", 1, 0, 12, 125000u, 8 },
	{ "LONG_SLOW", 1, 1, 12, 406250u, 8 },
	{ "LONG_TURBO", 9, 0, 11, 500000u, 8 },
	{ "LONG_TURBO", 9, 1, 11, 1625000u, 8 },
	{ "MEDIUM_FAST", 4, 0, 9, 250000u, 5 },
	{ "MEDIUM_FAST", 4, 1, 9, 812500u, 5 },
	{ "MEDIUM_SLOW", 3, 0, 10, 250000u, 5 },
	{ "MEDIUM_SLOW", 3, 1, 10, 812500u, 5 },
	{ "MEDIUM_TURBO", 16, 0, 9, 500000u, 5 },
	{ "MEDIUM_TURBO", 16, 1, 9, 1625000u, 5 },
	{ "NARROW_FAST", 12, 0, 7, 62500u, 6 },
	{ "NARROW_FAST", 12, 1, 7, 62500u, 6 },
	{ "NARROW_SLOW", 13, 0, 8, 62500u, 6 },
	{ "NARROW_SLOW", 13, 1, 8, 62500u, 6 },
	{ "SHORT_FAST", 6, 0, 7, 250000u, 5 },
	{ "SHORT_FAST", 6, 1, 7, 812500u, 5 },
	{ "SHORT_SLOW", 5, 0, 8, 250000u, 5 },
	{ "SHORT_SLOW", 5, 1, 8, 812500u, 5 },
	{ "SHORT_TURBO", 8, 0, 7, 500000u, 5 },
	{ "SHORT_TURBO", 8, 1, 7, 1625000u, 5 },
	{ "TINY_FAST", 14, 0, 7, 15600u, 5 },
	{ "TINY_FAST", 14, 1, 7, 15600u, 5 },
	{ "TINY_SLOW", 15, 0, 8, 15600u, 6 },
	{ "TINY_SLOW", 15, 1, 8, 15600u, 6 },
	{ "VERY_LONG_SLOW", 2, 0, 11, 250000u, 5 },
	{ "VERY_LONG_SLOW", 2, 1, 11, 812500u, 5 },
};

/* --- Preset display names (parity: radio D3 + crypto #1) -------------
 * Not cosmetic. `djb2` is the hash OF the display name, and that is what
 * selects the frequency slot. The display name also substitutes for an
 * empty channel name when computing the channel hash -- which is why the
 * port hardcoding "LongFast" is only correct while the modem is frozen
 * at LongFast. Get a string wrong and the node lands on the wrong
 * frequency AND the wrong channel hash, with no error anywhere.
 *
 * `_CUSTOM` is the use_preset=false literal, hashed the same way.
 */
struct mt_vec_preset_name {
	const char *preset;
	const char *display;
	const char *short_name;
	uint32_t djb2;
	uint8_t xor_hash;
};
static const struct mt_vec_preset_name mt_vec_preset_names[] = {
	{ "LITE_FAST", "LiteFast", "LiteF", 1203997249u, 20 },
	{ "LITE_SLOW", "LiteSlow", "LiteS", 1204476280u, 19 },
	{ "LONG_FAST", "LongFast", "LongF", 130429955u, 10 },
	{ "LONG_MODERATE", "LongMod", "LongM", 3908476213u, 108 },
	{ "LONG_SLOW", "LongSlow", "LongS", 130908986u, 13 },
	{ "LONG_TURBO", "LongTurbo", "LongT", 26541281u, 116 },
	{ "MEDIUM_FAST", "MediumFast", "MedF", 1461075348u, 29 },
	{ "MEDIUM_SLOW", "MediumSlow", "MedS", 1461554379u, 26 },
	{ "MEDIUM_TURBO", "MediumTurbo", "MedT", 988166290u, 99 },
	{ "NARROW_FAST", "NarrowFast", "NarF", 474665740u, 23 },
	{ "NARROW_SLOW", "NarrowSlow", "NarS", 475144771u, 16 },
	{ "SHORT_FAST", "ShortFast", "ShortF", 603668899u, 114 },
	{ "SHORT_SLOW", "ShortSlow", "ShortS", 604147930u, 117 },
	{ "SHORT_TURBO", "ShortTurbo", "ShortT", 2758524545u, 12 },
	{ "TINY_FAST", "TinyFast", "TinyF", 2638030743u, 10 },
	{ "TINY_SLOW", "TinySlow", "TinyS", 2638509774u, 13 },
	{ "VERY_LONG_SLOW", "Invalid", "Custom", 4242220u, 81 },
	{ "_CUSTOM", "Custom", "Custom", 2897143200u, 51 },
};

/* --- Region table (parity: radio D3 + airtime CP-1) ------------------
 * duty_cycle_pct is the regulatory ceiling. The port measures TX
 * airtime but never gates on it, so EU/UA builds can transmit past
 * the legal limit -- these are the numbers that enforcement needs.
 */
struct mt_vec_region {
	const char *name;
	float freq_start_mhz;
	float freq_end_mhz;
	float duty_cycle_pct;
	float power_limit_dbm;
	uint8_t wide_lora;
	const char *default_preset;
	uint32_t num_freq_slots;
	float slot_width_mhz;
};
static const struct mt_vec_region mt_vec_regions[] = {
	{ "US", 902.0f, 928.0f, 100.0f, 30.0f, 0, "LONG_FAST", 104u, 0.25f },
	{ "EU_433", 433.0f, 434.0f, 10.0f, 10.0f, 0, "LONG_FAST", 4u, 0.25f },
	{ "EU_868", 869.4f, 869.65f, 10.0f, 27.0f, 0, "LONG_FAST", 1u, 0.25f },
	{ "CN", 470.0f, 510.0f, 100.0f, 19.0f, 0, "LONG_FAST", 160u, 0.25f },
	{ "JP", 920.5f, 923.5f, 100.0f, 13.0f, 0, "LONG_FAST", 12u, 0.25f },
	{ "ANZ", 915.0f, 928.0f, 100.0f, 30.0f, 0, "LONG_FAST", 52u, 0.25f },
	{ "ANZ_433", 433.05f, 434.79f, 100.0f, 14.0f, 0, "LONG_FAST", 7u, 0.25f },
	{ "RU", 868.7f, 869.2f, 100.0f, 20.0f, 0, "LONG_FAST", 2u, 0.25f },
	{ "KR", 920.0f, 923.0f, 100.0f, 23.0f, 0, "LONG_FAST", 12u, 0.25f },
	{ "TW", 920.0f, 925.0f, 100.0f, 27.0f, 0, "LONG_FAST", 20u, 0.25f },
	{ "IN", 865.0f, 867.0f, 100.0f, 30.0f, 0, "LONG_FAST", 8u, 0.25f },
	{ "NZ_865", 864.0f, 868.0f, 100.0f, 36.0f, 0, "LONG_FAST", 16u, 0.25f },
	{ "TH", 920.0f, 925.0f, 10.0f, 27.0f, 0, "LONG_FAST", 20u, 0.25f },
	{ "UA_433", 433.0f, 434.7f, 10.0f, 10.0f, 0, "LONG_FAST", 7u, 0.25f },
	{ "MY_433", 433.0f, 435.0f, 100.0f, 20.0f, 0, "LONG_FAST", 8u, 0.25f },
	{ "MY_919", 919.0f, 924.0f, 100.0f, 27.0f, 0, "LONG_FAST", 20u, 0.25f },
	{ "SG_923", 917.0f, 925.0f, 100.0f, 20.0f, 0, "LONG_FAST", 32u, 0.25f },
	{ "PH_433", 433.0f, 434.7f, 100.0f, 10.0f, 0, "LONG_FAST", 7u, 0.25f },
	{ "PH_868", 868.0f, 869.4f, 100.0f, 14.0f, 0, "LONG_FAST", 6u, 0.25f },
	{ "PH_915", 915.0f, 918.0f, 100.0f, 24.0f, 0, "LONG_FAST", 12u, 0.25f },
	{ "KZ_433", 433.075f, 434.775f, 100.0f, 10.0f, 0, "LONG_FAST", 7u, 0.25f },
	{ "KZ_863", 863.0f, 868.0f, 100.0f, 30.0f, 0, "LONG_FAST", 20u, 0.25f },
	{ "NP_865", 865.0f, 868.0f, 100.0f, 30.0f, 0, "LONG_FAST", 12u, 0.25f },
	{ "BR_902", 902.0f, 907.5f, 100.0f, 30.0f, 0, "LONG_FAST", 22u, 0.25f },
	{ "LORA_24", 2400.0f, 2483.5f, 100.0f, 10.0f, 1, "LONG_FAST", 103u, 0.8125f },
	{ "UNSET", 902.0f, 928.0f, 100.0f, 30.0f, 0, "LONG_FAST", 104u, 0.25f },
};

/* --- Nonce layout (parity: crypto, security H1) ----------------------
 * 16-byte buffer; first 13 are used. Note the deliberate OVERLAP:
 * packetId is written as 8 bytes at offset 0, then a non-zero
 * extraNonce is written at offset 4 -- on top of packetId's high half.
 * A reimplementation that appends extraNonce instead produces a
 * plausible, wrong, and self-consistent nonce.
 */
struct mt_vec_nonce { const char *label; uint8_t nonce[16]; };
static const struct mt_vec_nonce mt_vec_nonces[] = {
	{ "psk_id1_from0", { 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } },
	{ "psk_id_max32", { 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } },
	{ "psk_id1_from_deadbeef", { 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xef, 0xbe, 0xad, 0xde, 0x00, 0x00, 0x00, 0x00 } },
	{ "psk_id_0102030405060708", { 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x00, 0x00, 0x00, 0x00 } },
	{ "pkc_extra_1", { 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0xef, 0xbe, 0xad, 0xde, 0x00, 0x00, 0x00, 0x00 } },
	{ "pkc_extra_aabbccdd", { 0x01, 0x00, 0x00, 0x00, 0xdd, 0xcc, 0xbb, 0xaa, 0xef, 0xbe, 0xad, 0xde, 0x00, 0x00, 0x00, 0x00 } },
	{ "pkc_bigid_extra", { 0x08, 0x07, 0x06, 0x05, 0xdd, 0xcc, 0xbb, 0xaa, 0x44, 0x33, 0x22, 0x11, 0x00, 0x00, 0x00, 0x00 } },
};

#define MT_VEC_COUNT(a) ((unsigned)(sizeof(a) / sizeof((a)[0])))

#endif /* MESHTASTIC_VECTORS_H_ */
